@baseUrl = http://localhost:3000/tasks
@id = d6019a35-4a85-41e0-af4b-e13e93afa1c0

GET {{baseUrl}}
###

POST  {{baseUrl}}
Content-Type: application/json

{
    "title": "My first task",
    "description": "This is my first task"
}

###
put  {{baseUrl}}/{{id}}
Content-Type: application/json

{
    "title": "khaled",
    "description": "This is my khaled task"
}

###
patch {{baseUrl}}/{{id}}


###
DELETE  {{baseUrl}}/{{id}}

